name: CI for Pull Requests

on:
  pull_request:
    branches:
      - main  # PR 대상 브랜치를 명시 (예: main 브랜치로의 PR)

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      # 1. 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Python 설정 (버전을 원하는 대로 수정)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # 원하는 Python 버전

      # 3. 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest  # 린터와 테스트 도구 설치
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. 린팅 실행
      - name: Run linter
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # 5. 테스트 실행
      - name: Run tests
        run: pytest

